baseURL = "https://www.whizz80.com"
languageCode = "en-US"
defaultContentLanguage = "en"

title = "Whizz80"
theme = "hugo-theme-learn"
metaDataFormat = "yaml"
defaultContentLanguageInSubdir= true

[params]
  editURL = ""
  description = "Whizz80 8-bit computer"
  author = "Phil Howlett"
  showVisitedLinks = true
  disableBreadcrumb = false
  disableNextPrev = false
  themeVariant = "blue"
  disbleLanguageSwitchingButton = true

[outputs]
home = [ "HTML", "RSS", "JSON"]

[menu]
  [[menu.shortcuts]]
    name = "<i class='fab fa-fw fa-github'></i> GitHub repo"
    identifier = "ds"
    url = "https://github.com/philbywhizz/whizz80"
    weight = 10

  [[menu.shortcuts]]
    name = "<i class='fas fa-fw fa-envelope'></i> Email"
    url = "mailto:phil.g.howlett@gmail.com"
    weight = 30

