baseURL: "https://whizz80.com"
languageCode: "en-US"
defaultContentLanguage: "en"

title: "Whizz80"
theme: "hugo-theme-learn"
metaDataFormat: "yaml"
defaultContentLanguageInSubdir: true

params:
  editURL: "https://github.com/Philbywhizz/whizz80.com/edit/main/content/"
  description: "Whizz80 8-bit computer"
  author: "Phil Howlett"
  showVisitedLinks: true
  disableBreadcrumb: false
  disableNextPrev: false
  disableMermaid: true
  themeVariant: "blue"
  disableLanguageSwitchingButton: true
  disableLandingPageButton: true

outputs:
  home:
    - HTML
    - RSS
    - JSON

menu:
  shortcuts:
  - name: "<i class='fab fa-fw fa-github'></i> GitHub repo"
    identifier: "ds"
    url: "https://github.com/philbywhizz/whizz80"
    weight: 10
  - name: "<i class='fas fa-fw fa-envelope'></i> Email"
    url: "mailto:phil.g.howlett@gmail.com"
    weight: 20
